eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true 
spring:
  application:
    name: Zuul-Microservice
server:
  port: 8083

zuul:
  routes:
    user: 
     path: /user/**
     service-id: User-Microservice
    note: 
     path: /note/**
     service-id: Note-MicroService
    label:
     path: /label/**
     service-id: Note-MicroService
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command: 
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000000000

  